### ISSUE TITLE
Testing on the NewYork paths

### ISSUE THREAD

**Issue by HernandoR** [theresejoseph/Trajectory_Tracking_via_MCAN#2]
Dear all

I ran a test on the shared New York paths with the result attached, which is fantastic.

Is there any explanation for the dorp in performance on the `path9`? or if it's unexpected and something's wrong with my configurations?
![result](https://github.com/theresejoseph/Trajectory_Tracking_via_MCAN/assets/45709656/15809e81-b590-4fa3-85d9-d8acabad8ac5)

**Comment by theresejoseph** [comment]
Hi, 

Glad to see you got the simulator working. What you see in path 9 is the controller for the kinematics motion model failing to follow the proposed path from the map. Since the tracks are randomly generated, this does happen in some instances. You can modify the control parameters in the vehicle class to get path 9 working, also the visualisation of the drive can show when the car deviates from the proposed track. 

Hope that helps :)

**Comment by HernandoR** [comment]
Thanks, I'll keep on doing that.
